apiVersion: v1
kind: Pod
metadata:
  name: soatapp
  labels:
    app: soatapp
spec:
  containers:
    - name: soatapp
      image: mateuspanda/soatapp:1
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: soatapp-configmap