apiVersion: apps/v1
kind: Deployment
metadata:
  name: soatapp-deployment
spec:
  template:
    metadata:
      name: soatapp
      labels:
        app: soatapp
    spec:
      containers:
        - name: soatapp
          image: mateuspanda/soatapp:1
          ports: 
            - containerPort: 3000
          envFrom: 
            - configMapRef:
                name: soatapp-configmap
  replicas: 3
  selector:
    matchLabels:
      app: soatapp