apiVersion: apps/v1
kind: Deployment
metadata:
  name: soatapp-deploymentt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soatapp
  template:
    metadata:
      labels:
        app: soatapp
    spec:
      containers:
      - name: soatapp
        image: mateuspanda/soatapp:1
        ports: 
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/v1/products
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/products
            port: 3000
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 30
        envFrom: 
          - configMapRef:
              name: soatapp-configmap
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: soat-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: soat-secrets
                key: AWS_SECRET_ACCESS_KEY
