apiVersion: v1
kind: Pod
metadata:
  name: soatapp-deployment
spec:
  containers:
  - name: soatapp
    image: gnoberto/soatapp:1
    ports: 
      - containerPort: 80
    envFrom:
        - configMapRef:
            name: soatapp-configmap