apiVersion: apps/v1
kind: Deployment
metadata:
  name: soatapp-deployment
spec:
  template:
    metadata:
      name: soatapp
      labels:
        app: soatapp
    spec:
      containers:
      - name: soatapp
        image: gnoberto/soatapp:1
        ports: 
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/v1/products
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/products
            port: 3000
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 30
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: soatapp-configmap
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: soatapp-configmap
                key: DB_PORT
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: soatapp-configmap
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: soatapp-configmap
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: soatapp-configmap
                key: DB_NAME
  replicas: 3
  selector:
    matchLabels:
      app: soatapp