name: soat-workflow
on: 
  push:
    branches: [ master, cicd ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    name: deploy ec2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2
    - name: Copy file ssh
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        # SOURCE: "./example"
        REMOTE_HOST: "ec2-18-189-184-37.us-east-2.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user"
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm install

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm install
  #   - run: npm test
  